In [16]:
#Adil Muhammed Ashraf PK
#AM.EN.U4CSE19003
#S5 CSE-A

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [5]:
data=pd.read_csv("merge.csv")
data.head()

,username,full_name,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes,is_fake
0,m_4_myran,0,0,0,72,0,6,19,0,0,0,1,0,0,0,0,0.0,0,0.0,1
1,imsorrymone_,üëø‡¥∑‡¥°‡µç‡¥°‡¥ø ‡¥µ‡¥ø‡¥±‡µç‡¥± ‡¥∏‡µÇ‡¥™‡µç‡¥™‡µº‡¥Æ‡¥æ‡µªüëø,0,0,85,0,9,12,0,0,0,0,0,0,0,0,23.0,0,0.0,1
2,vidhya_sree12,Sreevidhya,0,0,92,0,47,43,0,0,0,1,0,0,0,0,10.0,0,0.0,1
3,abcd.tharadas,‡¥ï‡µÄ‡¥∞‡¥ø‡¥ï‡µç‡¥ï‡¥æ‡¥ü‡µª ‡¥ú‡µá‡¥æ‡¥∏‡¥ø‡¥®‡µç‡¥±‡µÜ ‡¥Ö‡¥ö‡µç‡¥õ‡µª,0,0,26,0,49,20,0,0,1,0,2,0,3,0,27.0,2,1.5,1
4,s_a_c_h_i_n5434,SACHIN,0,1,0,0,22,95,0,0,0,0,0,0,0,0,6.0,0,0.0,1

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
Y=data["is_fake"]
X=data.loc[:, data.columns != 'is_fake']
print(Y.head())
print(X.head())

0    1
1    1
2    1
3    1
4    1
Name: is_fake, dtype: int64
          username                    full_name  is_verified  \
0        m_4_myran                            0            0
1     imsorrymone_      üëø‡¥∑‡¥°‡µç‡¥°‡¥ø ‡¥µ‡¥ø‡¥±‡µç‡¥± ‡¥∏‡µÇ‡¥™‡µç‡¥™‡µº‡¥Æ‡¥æ‡µªüëø            0
2    vidhya_sree12                   Sreevidhya            0
3    abcd.tharadas  ‡¥ï‡µÄ‡¥∞‡¥ø‡¥ï‡µç‡¥ï‡¥æ‡¥ü‡µª  ‡¥ú‡µá‡¥æ‡¥∏‡¥ø‡¥®‡µç‡¥±‡µÜ ‡¥Ö‡¥ö‡µç‡¥õ‡µª            0
4  s_a_c_h_i_n5434                       SACHIN            0

   has_anonymous_profile_picture  biography_len  external_url  followers  \
0                              0             72             0          6
1                              0             85             0          9
2                              0             92             0         47
3                              0             26             0         49
4                              1              0             0         22

   following  has_clips  highlight_count  is_professional_account  is_private  \
0         19          0                0                        0           1
1         12          0                0                        0           0
2         43          0                0                        0           1
3         20          0                0                        1           0
4         95          0                0                        0           0

   media_count  total_tags  total_likes  total_comments  name_length  \
0            0           0            0               0          0.0
1            0           0            0               0         23.0
2            0           0            0               0         10.0
3            2           0            3               0         27.0
4            0           0            0               0          6.0

   media_count_of_data_collected  average_likes
0                              0            0.0
1                              0            0.0
2                              0            0.0
3                              2            1.5
4                              0            0.0

In [8]:
normalized=pd.read_csv('merge.csv')
normalized.drop('username',inplace=True,axis=1)
normalized.drop('full_name',inplace=True,axis=1)
data=normalized
data.head(10)

,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes,is_fake
0,0,0,72,0,6,19,0,0,0,1,0,0,0,0,0.0,0,0.0,1
1,0,0,85,0,9,12,0,0,0,0,0,0,0,0,23.0,0,0.0,1
2,0,0,92,0,47,43,0,0,0,1,0,0,0,0,10.0,0,0.0,1
3,0,0,26,0,49,20,0,0,1,0,2,0,3,0,27.0,2,1.5,1
4,0,1,0,0,22,95,0,0,0,0,0,0,0,0,6.0,0,0.0,1
5,0,1,0,0,33,166,0,0,0,0,1,0,4,0,11.0,1,4.0,1
6,0,1,0,0,17,35,0,0,0,1,0,0,0,0,0.0,0,0.0,1
7,0,0,0,0,102,267,0,0,0,0,0,0,0,0,11.0,0,0.0,1
8,0,1,0,0,9,9,0,0,0,0,2,0,2,0,4.0,2,1.0,1
9,0,0,0,0,47,156,0,0,0,0,0,0,0,0,9.0,0,0.0,1

In [9]:
Y=data["is_fake"]
X=data.loc[:, data.columns != 'is_fake']
print(Y.head())
print(X.head())

0    1
1    1
2    1
3    1
4    1
Name: is_fake, dtype: int64
   is_verified  has_anonymous_profile_picture  biography_len  external_url  \
0            0                              0             72             0
1            0                              0             85             0
2            0                              0             92             0
3            0                              0             26             0
4            0                              1              0             0

   followers  following  has_clips  highlight_count  is_professional_account  \
0          6         19          0                0                        0
1          9         12          0                0                        0
2         47         43          0                0                        0
3         49         20          0                0                        1
4         22         95          0                0                        0

   is_private  media_count  total_tags  total_likes  total_comments  \
0           1            0           0            0               0
1           0            0           0            0               0
2           1            0           0            0               0
3           0            2           0            3               0
4           0            0           0            0               0

   name_length  media_count_of_data_collected  average_likes
0          0.0                              0            0.0
1         23.0                              0            0.0
2         10.0                              0            0.0
3         27.0                              2            1.5
4          6.0                              0            0.0

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state=1)
x_test.head(10)

,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes
861,0,0,0,0,173,287,0,0,0,1,1,0,42,0,12.0,1,42.000000
223,0,0,0,0,67,30,0,1,0,0,6,0,114,4,14.0,6,19.000000
84,0,1,0,0,28,495,0,0,0,0,0,0,0,0,9.0,0,0.000000
679,0,0,19,0,470,462,0,5,0,1,104,8,2192,66,14.0,12,182.666667
535,0,0,97,0,2677,959,1,9,1,0,11,31,3883,175,8.0,11,353.000000
622,0,0,148,0,105,56,0,8,0,1,42,0,438,28,7.0,12,36.500000
148,0,1,0,0,5,40,0,0,0,0,0,0,0,0,6.0,0,0.000000
3,0,0,26,0,49,20,0,0,1,0,2,0,3,0,27.0,2,1.500000
34,0,0,0,0,30,146,0,0,0,1,5,0,4,0,0.0,5,0.800000
241,0,0,22,0,251,691,0,6,0,0,4,0,267,59,6.0,4,66.750000

In [11]:
print (x_train)

     is_verified  has_anonymous_profile_picture  biography_len  external_url  \
35             0                              0            116             0
46             0                              0              0             0
453            0                              0              0             0
291            0                              0            135             0
747            0                              0             60             0
..           ...                            ...            ...           ...
715            0                              1              1             0
767            0                              0             98             0
72             0                              1              0             0
235            0                              0              4             0
37             0                              0             55             0

     followers  following  has_clips  highlight_count  \
35         192        139          0                0
46          10         15          0                0
453         90         46          1                0
291        115          2          1                5
747       1203        736          0                0
..         ...        ...        ...              ...
715          6          6          0                0
767       1143        837          1               25
72         127        463          0                0
235       3060        987          0                1
37          33         11          1                1

     is_professional_account  is_private  media_count  total_tags  \
35                         0           1            1           1
46                         0           0            1           0
453                        0           0           33           0
291                        1           0           27          52
747                        0           0            3           0
..                       ...         ...          ...         ...
715                        0           0            0           0
767                        1           0           52          41
72                         0           0            0           0
235                        1           0            3           5
37                         0           1           34           0

     total_likes  total_comments  name_length  media_count_of_data_collected  \
35            59              15         12.0                              1
46             0               0          0.0                              1
453           97               1          6.0                             12
291          653              93         28.0                             12
747          932              44         16.0                              3
..           ...             ...          ...                            ...
715            0               0          8.0                              0
767         5685             557         20.0                             12
72             0               0          0.0                              0
235          245              84          5.0                              3
37            18               0         11.0                             12

     average_likes
35       59.000000
46        0.000000
453       8.083333
291      54.416667
747     310.666667
..             ...
715       0.000000
767     473.750000
72        0.000000
235      81.666667
37        1.500000

[667 rows x 17 columns]

In [12]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(x_train, y_train)

In [14]:
classifier_predictions = clf.predict(x_test)
print(accuracy_score(y_test, classifier_predictions))

0.7533632286995515