In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

,username,full_name,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes,is_fake
0,_kriiishnaaa____,Krishna Rajeev,0,0,23,1,920,694,1,6,0,1,44,12,4289,237,14,12,357.416667,0
1,sim.run03,Simran Kathpalia,0,0,27,0,374,379,0,6,0,1,14,17,1473,189,16,12,122.750000,0
2,sarang_dileep_,Sarang Dileep,0,0,0,0,476,554,0,0,0,1,9,1,1086,75,13,9,120.666667,0
3,krishna_manoj._,KRISHNA MANOJ✨,0,0,23,0,524,516,0,5,0,1,0,0,0,0,14,0,0.000000,0
4,ritka_098,Ritika,0,1,0,0,680,775,0,12,0,1,0,0,0,0,6,0,0.000000,0
5,officialcjunior,aswin chandanaveli �️,0,0,36,1,907,916,1,11,1,0,58,17,2484,122,21,12,207.000000,0
6,sidharth.a_s_s,sidhartha sakthidharan,0,0,28,0,506,488,0,0,0,1,13,17,1603,98,22,12,133.583333,0
7,_adil1._,Adil Ashraf,0,0,0,0,1486,809,0,12,1,0,18,82,5816,229,11,12,484.666667,0
8,itzz_me__anu,Anugraha,0,0,32,0,363,433,0,12,0,1,5,7,983,85,8,5,196.600000,0
9,_vipulv,ѴιƤʋ˩ Ѵ,0,0,85,0,422,417,1,12,0,0,16,50,2194,470,7,12,182.833333,0

In [3]:
dropping=pd.read_csv('fake_genuine_merge.csv')
dropping.drop('username',inplace=True,axis=1)
dropping.drop('full_name',inplace=True,axis=1)
data=dropping
data.head()

,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes,is_fake
0,0,0,23,1,920,694,1,6,0,1,44,12,4289,237,14,12,357.416667,0
1,0,0,27,0,374,379,0,6,0,1,14,17,1473,189,16,12,122.750000,0
2,0,0,0,0,476,554,0,0,0,1,9,1,1086,75,13,9,120.666667,0
3,0,0,23,0,524,516,0,5,0,1,0,0,0,0,14,0,0.000000,0
4,0,1,0,0,680,775,0,12,0,1,0,0,0,0,6,0,0.000000,0

In [4]:
Y=data["is_fake"]
X=data.loc[:, data.columns != 'is_fake']
print(Y.head())

0    0
1    0
2    0
3    0
4    0
Name: is_fake, dtype: int64

In [5]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.40)
x_train

,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes
428,0,0,52,0,968,983,0,0,0,1,16,68,3235,368,9,12,269.583333
309,0,0,28,1,1900,672,0,38,0,1,245,16,3512,724,17,12,292.666667
856,0,0,96,0,1930,1116,0,1,1,0,2,4,218,4,13,2,109.000000
667,0,1,0,0,86,1970,0,0,0,0,0,0,0,0,13,0,0.000000
307,0,0,110,0,793,830,0,3,0,1,0,0,0,0,20,0,0.000000
867,0,0,0,0,50,115,0,0,0,0,10,0,55,2,13,10,5.500000
538,0,0,17,1,137,364,1,0,0,0,1,0,8,3,15,1,8.000000
592,0,0,1,0,110,172,0,0,0,0,2,0,84,24,5,2,42.000000
35,0,0,2,0,741,457,0,0,0,1,7,9,1336,9,16,7,190.857143
46,0,0,132,0,106,172,1,1,0,0,9,1,278,99,10,9,30.888889
447,0,0,0,0,125,158,0,0,0,0,5,6,325,57,22,5,65.000000
422,0,0,0,0,137,228,0,3,0,0,13,8,621,39,14,12,51.750000
769,0,0,41,0,82,37,0,0,0,0,20,2,124,32,4,12,10.333333
41,0,0,143,1,590,509,1,3,1,0,4,10,1075,186,13,4,268.750000
224,0,0,51,0,186,182,0,8,0,1,28,43,966,208,0,12,80.500000
349,0,0,41,1,730,819,1,3,1,0,122,0,962,182,17,12,80.166667
125,0,0,31,0,831,1006,0,0,1,0,23,0,3056,103,15,12,254.666667
429,0,0,80,0,972,982,0,0,0,1,37,53,4398,258,13,12,366.500000
659,0,1,0,0,12,22,0,0,0,0,0,0,0,0,0,0,0.000000
108,0,0,15,1,648,792,1,0,0,0,134,1,2430,98,16,12,202.500000
582,0,1,0,0,12,355,0,0,0,0,0,0,0,0,0,0,0.000000
893,0,1,0,0,364,2336,0,2,0,0,0,0,0,0,13,0,0.000000
110,0,0,45,0,205,195,0,0,0,1,0,0,0,0,23,0,0.000000
375,0,0,98,0,615,586,0,1,0,1,13,15,2850,248,11,12,237.500000
0,0,0,23,1,920,694,1,6,0,1,44,12,4289,237,14,12,357.416667
457,0,0,0,0,580,1205,0,0,0,1,0,0,0,0,13,0,0.000000
729,0,0,105,0,655,804,1,16,1,0,10,7,684,36,19,10,68.400000
584,0,1,0,0,28,495,0,0,0,0,0,0,0,0,9,0,0.000000
74,0,0,19,0,480,506,1,0,0,0,0,0,0,0,5,0,0.000000
160,0,0,99,0,491,488,0,0,0,1,9,1,2201,231,16,9,244.555556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
864,0,0,0,0,65,190,0,0,0,0,4,0,9,0,22,4,2.250000
478,0,0,25,0,1585,988,0,0,0,1,5,2,1976,34,9,5,395.200000
503,0,0,26,0,49,20,0,0,1,0,2,0,3,0,27,2,1.500000
753,0,0,2,0,754,1481,1,0,1,0,15,0,644,26,16,12,53.666667
215,0,0,99,0,651,882,0,15,0,1,7,6,2038,135,13,7,291.142857
580,0,1,0,0,265,208,1,2,1,0,11,29,1013,36,8,11,92.090909
562,0,1,0,0,5,33,0,0,0,1,0,0,0,0,10,0,0.000000
398,0,0,36,0,105,115,1,0,1,0,25,10,648,51,3,12,54.000000
668,0,1,0,0,275,210,0,0,0,0,0,0,0,0,11,0,0.000000
490,0,0,2,0,629,1306,0,0,0,0,3,3,694,126,15,3,231.333333
252,0,0,0,0,1000,928,0,3,0,1,9,14,2681,101,7,9,297.888889
468,0,0,33,0,537,606,1,1,0,1,3,2,687,68,6,3,229.000000
357,0,0,29,0,532,528,0,7,0,1,2,1,439,17,25,2,219.500000
254,0,0,44,0,285,288,0,0,0,1,2,1,293,62,8,2,146.500000
276,0,0,17,0,447,436,0,4,0,1,9,43,952,161,12,9,105.777778
178,0,1,20,0,324,242,0,2,0,1,0,0,0,0,15,0,0.000000
281,0,0,35,0,401,451,0,0,0,1,3,2,541,30,12,3,180.333333
390,0,1,0,0,460,641,0,0,0,1,5,19,873,180,9,5,174.600000
508,0,1,0,0,9,9,0,0,0,0,2,0,2,0,4,2,1.000000
749,0,1,106,0,1260,1202,1,1,0,0,8,15,619,39,22,8,77.375000
583,0,0,46,0,73,114,0,0,0,0,0,0,0,0,7,0,0.000000
129,0,0,0,0,167,218,0,0,0,0,5,0,155,7,8,5,31.000000
144,0,0,0,0,193,223,0,0,0,0,1,0,68,14,4,1,68.000000
847,0,0,0,0,183,28,0,0,0,0,0,0,0,0,14,0,0.000000
645,0,1,0,0,8,13,0,0,0,0,0,0,0,0,10,0,0.000000
715,0,0,70,0,95,99,0,1,0,1,6,0,73,4,10,6,12.166667
767,0,0,66,0,6027,360,0,0,0,1,2,0,1925,421,5,2,962.500000
72,0,0,0,0,142,170,0,0,0,1,7,0,306,54,12,7,43.714286
235,0,0,13,0,184,141,0,0,0,0,3,0,82,1,10,3,27.333333
37,0,0,26,0,489,514,0,2,0,1,10,11,944,43,18,10,94.400000

In [6]:
scaler = StandardScaler()#gaved best accuracy than normalisation
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_train

array([[ 0.        , -0.46388563,  0.40659777, ..., -0.21830095,
         1.40321413,  0.59633254],
       [ 0.        , -0.46388563, -0.15832373, ...,  1.15111083,
         1.40321413,  0.68789517],
       [ 0.        , -0.46388563,  1.44228718, ...,  0.46640494,
        -0.58615274, -0.04063924],
       ...,
       [ 0.        , -0.46388563, -0.81739882, ...,  0.29522847,
         0.4085307 , -0.29960234],
       [ 0.        , -0.46388563, -0.51139967, ..., -0.04712448,
        -0.38721605, -0.36457922],
       [ 0.        , -0.46388563, -0.20540053, ...,  1.3222873 ,
         1.00534076, -0.09855178]])

In [7]:
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0])

In [8]:
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
print("\n")
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2*100)

Confusion Matrix:
[[104  15]
 [ 21  84]]


Accuracy: 83.92857142857143

In [9]:
high=-1
for i in range(1,13):
    classifier = KNeighborsClassifier(n_neighbors = i)
    classifier.fit(x_train, y_train)
    y_pred = classifier.predict(x_test)
    results = accuracy_score(y_test,y_pred)
    if((results)*100 > high):
        high=(results)*100
        output=i
print("best k="+str(output))

best k=12