In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
data=pd.read_csv('fake_genuine_merge.csv',header=0)
data.head(10)

,username,full_name,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes,is_fake
0,_kriiishnaaa____,Krishna Rajeev,0,0,23,1,920,694,1,6,0,1,44,12,4289,237,14,12,357.416667,0
1,sim.run03,Simran Kathpalia,0,0,27,0,374,379,0,6,0,1,14,17,1473,189,16,12,122.750000,0
2,sarang_dileep_,Sarang Dileep,0,0,0,0,476,554,0,0,0,1,9,1,1086,75,13,9,120.666667,0
3,krishna_manoj._,KRISHNA MANOJ✨,0,0,23,0,524,516,0,5,0,1,0,0,0,0,14,0,0.000000,0
4,ritka_098,Ritika,0,1,0,0,680,775,0,12,0,1,0,0,0,0,6,0,0.000000,0
5,officialcjunior,aswin chandanaveli �️,0,0,36,1,907,916,1,11,1,0,58,17,2484,122,21,12,207.000000,0
6,sidharth.a_s_s,sidhartha sakthidharan,0,0,28,0,506,488,0,0,0,1,13,17,1603,98,22,12,133.583333,0
7,_adil1._,Adil Ashraf,0,0,0,0,1486,809,0,12,1,0,18,82,5816,229,11,12,484.666667,0
8,itzz_me__anu,Anugraha,0,0,32,0,363,433,0,12,0,1,5,7,983,85,8,5,196.600000,0
9,_vipulv,ѴιƤʋ˩ Ѵ,0,0,85,0,422,417,1,12,0,0,16,50,2194,470,7,12,182.833333,0

In [3]:
dropping=pd.read_csv('fake_genuine_merge.csv')
dropping.drop('username',inplace=True,axis=1)
dropping.drop('full_name',inplace=True,axis=1)
data=dropping
data.head()

,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes,is_fake
0,0,0,23,1,920,694,1,6,0,1,44,12,4289,237,14,12,357.416667,0
1,0,0,27,0,374,379,0,6,0,1,14,17,1473,189,16,12,122.750000,0
2,0,0,0,0,476,554,0,0,0,1,9,1,1086,75,13,9,120.666667,0
3,0,0,23,0,524,516,0,5,0,1,0,0,0,0,14,0,0.000000,0
4,0,1,0,0,680,775,0,12,0,1,0,0,0,0,6,0,0.000000,0

In [4]:
Y=data["is_fake"]
X=data.loc[:, data.columns != 'is_fake']
print(Y.head())

0    0
1    0
2    0
3    0
4    0
Name: is_fake, dtype: int64

In [5]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.40)
x_train

,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes
312,0,0,29,0,502,475,0,5,0,1,16,18,1884,151,9,12,157.000000
136,0,0,12,0,319,422,0,0,0,0,27,20,1217,88,9,12,101.416667
94,0,1,0,0,500,489,0,0,1,0,3,24,528,33,7,3,176.000000
227,0,0,75,0,858,1002,0,1,1,0,95,21,2488,68,4,12,207.333333
814,0,0,43,0,626,622,0,1,0,0,1,0,48,2,10,1,48.000000
820,0,0,12,0,562,1093,1,1,0,0,2,0,150,8,17,2,75.000000
466,0,0,8,0,16405,581,1,2,0,1,12,8,27464,646,11,12,2288.666667
436,0,0,33,0,393,517,0,5,1,0,30,19,1270,44,6,12,105.833333
608,0,1,0,0,357,925,0,0,0,0,9,0,202,7,8,9,22.444444
51,0,0,52,0,530,336,0,6,0,1,0,0,0,0,13,0,0.000000
126,0,0,30,0,683,791,0,0,0,1,5,13,1575,192,8,5,315.000000
281,0,0,35,0,401,451,0,0,0,1,3,2,541,30,12,3,180.333333
770,0,0,41,0,107,127,0,0,0,1,0,0,0,0,8,0,0.000000
264,0,0,0,0,89,195,0,0,0,1,9,0,143,5,6,9,15.888889
426,0,0,39,0,665,734,0,3,0,1,0,0,0,0,10,0,0.000000
876,0,0,0,0,733,6708,0,0,0,0,0,0,0,0,13,0,0.000000
477,0,0,64,0,306,612,0,2,0,1,11,5,1709,221,21,11,155.363636
170,0,0,55,0,531,534,0,5,0,1,6,10,1421,206,8,6,236.833333
40,0,0,128,0,393,761,0,3,0,1,9,9,906,59,11,9,100.666667
155,0,0,0,0,457,560,0,0,0,0,4,0,486,43,26,4,121.500000
8,0,0,32,0,363,433,0,12,0,1,5,7,983,85,8,5,196.600000
783,0,1,0,0,3,3,0,0,0,0,0,0,0,0,0,0,0.000000
198,0,0,1,0,619,694,0,3,0,1,11,24,2708,315,13,11,246.181818
168,0,0,0,0,450,486,0,0,0,1,7,10,1466,83,16,7,209.428571
823,0,0,11,0,878,935,0,0,0,0,95,20,142,4,23,12,11.833333
880,0,0,0,0,74,421,0,0,0,0,0,0,0,0,3,0,0.000000
376,0,0,29,0,728,1003,0,0,0,1,0,0,0,0,5,0,0.000000
676,0,0,0,0,180,747,0,0,0,0,7,0,132,1,4,7,18.857143
233,0,0,1,0,391,562,0,7,0,1,15,28,2490,366,14,12,207.500000
839,0,0,116,1,1294,5,0,2,1,0,2,1,87,4,30,2,43.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,0,0,68,1,292,352,0,1,0,1,35,26,1424,51,17,12,118.666667
308,0,0,66,0,919,974,0,0,0,1,0,0,0,0,9,0,0.000000
552,0,0,35,0,51,196,0,0,1,0,0,0,0,0,7,0,0.000000
835,0,0,46,0,147,62,0,0,0,0,0,0,0,0,12,0,0.000000
573,0,0,0,0,8,41,0,0,0,1,0,0,0,0,0,0,0.000000
59,0,0,0,0,342,339,0,0,0,1,0,0,0,0,12,0,0.000000
180,0,0,11,0,541,777,0,0,0,0,80,0,1666,122,16,12,138.833333
517,0,0,0,0,1,2,0,0,0,1,0,0,0,0,0,0,0.000000
337,0,0,0,0,167,231,0,0,0,0,5,0,181,4,15,5,36.200000
810,0,0,0,0,20,25,0,0,0,0,0,0,0,0,0,0,0.000000
583,0,0,46,0,73,114,0,0,0,0,0,0,0,0,7,0,0.000000
743,0,0,0,0,167,214,0,1,0,0,3,3,155,4,8,3,51.666667
762,0,0,0,0,933,5443,0,1,0,0,0,0,0,0,6,0,0.000000
711,0,0,119,0,377,444,0,0,0,1,0,0,0,0,6,0,0.000000
681,0,0,37,0,387,245,0,1,0,1,0,0,0,0,4,0,0.000000
491,0,0,51,0,274,455,0,0,0,0,1,0,76,7,15,1,76.000000
429,0,0,80,0,972,982,0,0,0,1,37,53,4398,258,13,12,366.500000
120,0,0,20,0,932,4526,0,0,0,0,5,1,739,16,15,5,147.800000
315,0,0,62,0,252,507,0,0,0,0,0,0,0,0,12,0,0.000000
505,0,1,0,0,33,166,0,0,0,0,1,0,4,0,11,1,4.000000
129,0,0,0,0,167,218,0,0,0,0,5,0,155,7,8,5,31.000000
577,0,0,36,0,10,434,0,2,1,0,2,0,3,0,10,2,1.500000
715,0,0,70,0,95,99,0,1,0,1,6,0,73,4,10,6,12.166667
199,0,0,28,0,131,142,0,0,0,0,0,0,0,0,4,0,0.000000
690,0,0,0,0,186,672,0,0,0,0,1,0,64,14,18,1,64.000000
215,0,0,99,0,651,882,0,15,0,1,7,6,2038,135,13,7,291.142857
225,0,0,52,0,594,1139,0,0,0,1,46,37,2766,276,12,12,230.500000
238,0,0,98,1,442,407,0,2,1,0,0,0,0,0,19,0,0.000000
471,0,0,111,0,1217,1212,0,1,0,1,6,15,1658,67,8,6,276.333333
638,0,0,0,0,101,20,0,0,0,0,0,0,0,0,11,0,0.000000

In [6]:
scaler = StandardScaler()#gaved best accuracy than normalisation
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_train

array([[ 0.        , -0.43061638, -0.14918105, ..., -0.18199713,
         1.45401193,  0.23085173],
       [ 0.        , -0.43061638, -0.55091372, ..., -0.18199713,
         1.45401193, -0.03473858],
       [ 0.        ,  2.3222526 , -0.83448973, ..., -0.53418617,
        -0.35806637,  0.32163822],
       ...,
       [ 0.        , -0.43061638,  1.48138099, ...,  1.57894807,
        -0.96209247, -0.5193314 ],
       [ 0.        , -0.43061638,  1.78858833, ..., -0.35809165,
         0.24595973,  0.80105462],
       [ 0.        , -0.43061638, -0.83448973, ...,  0.17019191,
        -0.96209247, -0.5193314 ]])

In [7]:
classifier = KNeighborsClassifier(n_neighbors = 5)
print(x_train)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
len(y_pred)

[[ 0.         -0.43061638 -0.14918105 ... -0.18199713  1.45401193
   0.23085173]
 [ 0.         -0.43061638 -0.55091372 ... -0.18199713  1.45401193
  -0.03473858]
 [ 0.          2.3222526  -0.83448973 ... -0.53418617 -0.35806637
   0.32163822]
 ...
 [ 0.         -0.43061638  1.48138099 ...  1.57894807 -0.96209247
  -0.5193314 ]
 [ 0.         -0.43061638  1.78858833 ... -0.35809165  0.24595973
   0.80105462]
 [ 0.         -0.43061638 -0.83448973 ...  0.17019191 -0.96209247
  -0.5193314 ]]

359

In [8]:
len(y_test)

359

In [9]:
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
print("\n")
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2*100)

Confusion Matrix:
[[175  34]
 [ 27 123]]


Accuracy: 83.008356545961

In [10]:
high=-1
for i in range(1,13):
    classifier = KNeighborsClassifier(n_neighbors = i)
    classifier.fit(x_train, y_train)
    y_pred = classifier.predict(x_test)
    results = accuracy_score(y_test,y_pred)
    if((results)*100 > high):
        high=(results)*100
        output=i
print("best k="+str(output))

best k=4

# KFold

In [11]:
def accuracy(Y_pred,Y_test):
    Y_test=Y_test.values
    count=0
    for i in range(0,len(Y_pred)):
        if(Y_pred[i]==Y_test[i]):
            count=count+1
    print("accuracy of kfold :"+str((count/len(Y_pred))*100))
    return (count/len(Y_pred))*100

mean=0


import pandas as pd
from sklearn.model_selection import KFold
data=(data-data.min())/(data.max()-data.min())
data.drop('is_verified',inplace=True, axis=1)
Y_train=data["is_fake"]
X_train=data.loc[:, data.columns != 'is_fake']
cv = KFold(n_splits=4, random_state=1, shuffle=True)
kfold=cv.split(X_train, Y_train)
for k, (train, test) in enumerate(kfold):
    classifier.fit(X_train.iloc[train, :], Y_train.iloc[train])
    Y_pred=classifier.predict(X_train.iloc[test, :])
    mean=mean+accuracy(Y_pred,Y_train.iloc[test])
print(mean/4)

accuracy of kfold :83.92857142857143
accuracy of kfold :78.57142857142857
accuracy of kfold :84.82142857142857
accuracy of kfold :75.44642857142857
80.69196428571428

# Sayooj B Kumar

## AM.EN.U4CSE19050