In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
data=pd.read_csv('fake_genuine_merge.csv',header=0)
data.head(10)

,username,full_name,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes,is_fake
0,_kriiishnaaa____,Krishna Rajeev,0,0,23,1,920,694,1,6,0,1,44,12,4289,237,14,12,357.416667,0
1,sim.run03,Simran Kathpalia,0,0,27,0,374,379,0,6,0,1,14,17,1473,189,16,12,122.750000,0
2,sarang_dileep_,Sarang Dileep,0,0,0,0,476,554,0,0,0,1,9,1,1086,75,13,9,120.666667,0
3,krishna_manoj._,KRISHNA MANOJ✨,0,0,23,0,524,516,0,5,0,1,0,0,0,0,14,0,0.000000,0
4,ritka_098,Ritika,0,1,0,0,680,775,0,12,0,1,0,0,0,0,6,0,0.000000,0
5,officialcjunior,aswin chandanaveli �️,0,0,36,1,907,916,1,11,1,0,58,17,2484,122,21,12,207.000000,0
6,sidharth.a_s_s,sidhartha sakthidharan,0,0,28,0,506,488,0,0,0,1,13,17,1603,98,22,12,133.583333,0
7,_adil1._,Adil Ashraf,0,0,0,0,1486,809,0,12,1,0,18,82,5816,229,11,12,484.666667,0
8,itzz_me__anu,Anugraha,0,0,32,0,363,433,0,12,0,1,5,7,983,85,8,5,196.600000,0
9,_vipulv,ѴιƤʋ˩ Ѵ,0,0,85,0,422,417,1,12,0,0,16,50,2194,470,7,12,182.833333,0

In [3]:
dropping=pd.read_csv('fake_genuine_merge.csv')
dropping.drop('username',inplace=True,axis=1)
dropping.drop('full_name',inplace=True,axis=1)
data=dropping
data.head()

,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes,is_fake
0,0,0,23,1,920,694,1,6,0,1,44,12,4289,237,14,12,357.416667,0
1,0,0,27,0,374,379,0,6,0,1,14,17,1473,189,16,12,122.750000,0
2,0,0,0,0,476,554,0,0,0,1,9,1,1086,75,13,9,120.666667,0
3,0,0,23,0,524,516,0,5,0,1,0,0,0,0,14,0,0.000000,0
4,0,1,0,0,680,775,0,12,0,1,0,0,0,0,6,0,0.000000,0

In [4]:
Y=data["is_fake"]
X=data.loc[:, data.columns != 'is_fake']
print(Y.head())

0    0
1    0
2    0
3    0
4    0
Name: is_fake, dtype: int64

In [5]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.40)
x_train

,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes
656,0,0,0,0,149,77,0,0,0,0,0,0,0,0,8,0,0.000000
621,0,0,0,0,10,98,0,0,0,1,0,0,0,0,14,0,0.000000
321,0,0,49,0,619,684,0,4,0,1,37,42,2313,98,12,12,192.750000
624,0,1,24,0,115,553,0,0,0,0,0,0,0,0,0,0,0.000000
1,0,0,27,0,374,379,0,6,0,1,14,17,1473,189,16,12,122.750000
208,0,0,0,0,509,562,0,0,0,1,3,1,772,87,8,3,257.333333
235,0,0,13,0,184,141,0,0,0,0,3,0,82,1,10,3,27.333333
681,0,0,37,0,387,245,0,1,0,1,0,0,0,0,4,0,0.000000
88,0,1,10,0,398,456,0,0,0,0,2,3,394,80,13,2,197.000000
184,0,0,0,0,225,245,0,1,0,1,0,0,0,0,6,0,0.000000
200,0,0,0,0,156,171,0,0,0,1,0,0,0,0,11,0,0.000000
239,0,0,150,0,202,507,0,7,0,1,21,0,565,13,11,12,47.083333
380,0,0,0,0,134,164,0,0,0,1,3,0,67,0,19,3,22.333333
21,0,0,4,0,35,34,0,0,0,1,2,0,31,5,0,2,15.500000
826,0,0,46,0,268,164,0,0,0,0,7,0,228,7,10,7,32.571429
293,0,0,101,1,801,1456,0,0,0,1,0,0,0,0,13,0,0.000000
435,0,0,138,1,1152,702,0,3,0,0,64,61,2162,55,14,12,180.166667
662,0,0,95,0,53,159,0,0,1,0,0,0,0,0,16,0,0.000000
53,0,0,124,0,1081,982,0,6,1,0,19,4,4470,593,18,12,372.500000
680,0,1,0,0,194,1857,0,0,0,0,0,0,0,0,11,0,0.000000
454,0,0,2,0,691,933,0,1,0,1,1,1,276,40,25,1,276.000000
790,0,0,0,0,338,1390,0,0,1,0,0,0,0,0,5,0,0.000000
838,0,0,18,0,49,206,0,3,1,0,1,0,9,0,0,1,9.000000
9,0,0,85,0,422,417,1,12,0,0,16,50,2194,470,7,12,182.833333
881,0,0,0,0,857,168,0,0,0,0,2,0,410,28,7,2,205.000000
229,0,0,0,0,63,85,0,0,0,0,0,0,0,0,15,0,0.000000
238,0,0,98,1,442,407,0,2,1,0,0,0,0,0,19,0,0.000000
660,0,1,0,0,4,28,0,0,0,0,0,0,0,0,0,0,0.000000
748,0,0,11,0,812,386,0,2,0,1,1,0,60,7,6,1,60.000000
676,0,0,0,0,180,747,0,0,0,0,7,0,132,1,4,7,18.857143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,0,82,0,313,1665,0,5,1,0,54,0,987,6,12,12,82.250000
750,0,0,106,0,1073,491,0,5,0,0,4,0,734,116,6,4,183.500000
143,0,0,68,1,292,352,0,1,0,1,35,26,1424,51,17,12,118.666667
423,0,0,81,1,348,450,1,12,0,1,44,43,1330,78,19,12,110.833333
144,0,0,0,0,193,223,0,0,0,0,1,0,68,14,4,1,68.000000
281,0,0,35,0,401,451,0,0,0,1,3,2,541,30,12,3,180.333333
603,0,1,0,0,17,225,0,0,1,0,1,0,3,0,5,1,3.000000
451,0,0,0,1,410,665,0,2,0,1,6,30,776,90,8,6,129.333333
97,0,0,17,0,136,125,0,0,0,1,0,0,0,0,6,0,0.000000
506,0,1,0,0,17,35,0,0,0,1,0,0,0,0,0,0,0.000000
606,0,1,0,0,16,100,0,0,0,0,0,0,0,0,0,0,0.000000
395,0,0,0,0,997,781,1,4,0,0,28,7,3307,295,15,12,275.583333
876,0,0,0,0,733,6708,0,0,0,0,0,0,0,0,13,0,0.000000
140,0,0,21,0,100,100,0,0,0,1,14,9,584,65,0,12,48.666667
289,0,0,117,0,451,307,0,5,0,1,9,3,1666,115,14,9,185.111111
178,0,1,20,0,324,242,0,2,0,1,0,0,0,0,15,0,0.000000
212,0,0,0,0,273,300,0,0,0,0,1,6,85,4,10,1,85.000000
206,0,0,63,0,666,1049,0,0,0,1,12,3,2310,71,16,12,192.500000
767,0,0,66,0,6027,360,0,0,0,1,2,0,1925,421,5,2,962.500000
740,0,0,51,0,194,346,0,0,0,0,1,0,94,10,13,1,94.000000
134,0,0,33,0,397,379,0,2,0,1,12,0,1512,150,17,12,126.000000
587,0,1,0,0,26,34,0,0,0,0,0,0,0,0,7,0,0.000000
667,0,1,0,0,86,1970,0,0,0,0,0,0,0,0,13,0,0.000000
327,0,0,0,1,327,497,0,1,0,0,8,11,541,3,13,8,67.625000
728,0,0,88,0,133,27,0,2,0,0,6,0,77,0,17,6,12.833333
367,0,0,65,0,517,508,0,0,0,1,3,3,483,34,16,3,161.000000
296,0,0,0,0,484,532,0,1,0,1,2,7,385,9,11,2,192.500000
894,0,0,0,0,279,3245,0,0,0,0,2,0,483,7,3,2,241.500000
306,0,0,31,1,130,4,0,0,1,0,3,7,173,0,17,3,57.666667
151,0,0,28,0,421,461,0,1,0,1,20,13,1780,143,12,12,148.333333

In [6]:
svc = svm.SVC()
svc.fit(x_train, y_train)

SVC()

In [8]:
y_pred = svc.predict(x_test)
print(y_pred)

[0 1 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1
 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 0 1 1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 1 1 1 1
 0 1 1 0 0 0 1 0 0 1 1 1 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 1 1 1 1 0 1 0 1 0
 1 1 0 1 1 1 1 1 1 0 1 1 0 1 0 1 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 0 1 1 1
 1 0 1 0 1 0 1 1 1 0 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0
 0 1 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 0 1 1
 1 0 1 1 1 0 0 1 1 0 0 0 1 1 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 0 0 0 0 1 1 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 0 0 1 0
 1 0 0 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0]

In [9]:
confusion_matrix(y_test, y_pred)

array([[131,  81],
       [ 11, 136]])

In [12]:
result = accuracy_score(y_test,y_pred)
print("Accuracy:",result*100)

Accuracy: 74.3732590529248

# Sayooj B Kumar

## AM.EN.U4CSE19050