# SVM Model

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
data=pd.read_csv('fake_genuine_merge.csv',header=0)
data.head(10)

,username,full_name,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes,is_fake
0,_kriiishnaaa____,Krishna Rajeev,0,0,23,1,920,694,1,6,0,1,44,12,4289,237,14,12,357.416667,0
1,sim.run03,Simran Kathpalia,0,0,27,0,374,379,0,6,0,1,14,17,1473,189,16,12,122.750000,0
2,sarang_dileep_,Sarang Dileep,0,0,0,0,476,554,0,0,0,1,9,1,1086,75,13,9,120.666667,0
3,krishna_manoj._,KRISHNA MANOJ✨,0,0,23,0,524,516,0,5,0,1,0,0,0,0,14,0,0.000000,0
4,ritka_098,Ritika,0,1,0,0,680,775,0,12,0,1,0,0,0,0,6,0,0.000000,0
5,officialcjunior,aswin chandanaveli �️,0,0,36,1,907,916,1,11,1,0,58,17,2484,122,21,12,207.000000,0
6,sidharth.a_s_s,sidhartha sakthidharan,0,0,28,0,506,488,0,0,0,1,13,17,1603,98,22,12,133.583333,0
7,_adil1._,Adil Ashraf,0,0,0,0,1486,809,0,12,1,0,18,82,5816,229,11,12,484.666667,0
8,itzz_me__anu,Anugraha,0,0,32,0,363,433,0,12,0,1,5,7,983,85,8,5,196.600000,0
9,_vipulv,ѴιƤʋ˩ Ѵ,0,0,85,0,422,417,1,12,0,0,16,50,2194,470,7,12,182.833333,0

In [3]:
dropping=pd.read_csv('fake_genuine_merge.csv')
dropping.drop('username',inplace=True,axis=1)
dropping.drop('full_name',inplace=True,axis=1)
data=dropping
data.head()

,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes,is_fake
0,0,0,23,1,920,694,1,6,0,1,44,12,4289,237,14,12,357.416667,0
1,0,0,27,0,374,379,0,6,0,1,14,17,1473,189,16,12,122.750000,0
2,0,0,0,0,476,554,0,0,0,1,9,1,1086,75,13,9,120.666667,0
3,0,0,23,0,524,516,0,5,0,1,0,0,0,0,14,0,0.000000,0
4,0,1,0,0,680,775,0,12,0,1,0,0,0,0,6,0,0.000000,0

In [4]:
Y=data["is_fake"]
X=data.loc[:, data.columns != 'is_fake']
print(Y.head())

0    0
1    0
2    0
3    0
4    0
Name: is_fake, dtype: int64

In [5]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.40)
x_train

,is_verified,has_anonymous_profile_picture,biography_len,external_url,followers,following,has_clips,highlight_count,is_professional_account,is_private,media_count,total_tags,total_likes,total_comments,name_length,media_count_of_data_collected,average_likes
163,0,0,0,0,449,495,0,0,0,1,0,0,0,0,12,0,0.000000
181,0,0,0,0,62,98,0,0,0,1,6,1,50,2,15,6,8.333333
412,0,0,0,0,31,38,0,0,0,1,0,0,0,0,11,0,0.000000
178,0,1,20,0,324,242,0,2,0,1,0,0,0,0,15,0,0.000000
86,0,0,0,0,405,410,0,0,0,1,3,2,334,39,13,3,111.333333
649,0,0,0,0,183,354,0,0,0,0,0,0,0,0,10,0,0.000000
654,0,1,0,0,7,32,0,0,0,0,0,0,0,0,0,0,0.000000
192,0,0,12,0,1214,764,0,0,0,1,24,13,4264,339,14,12,355.333333
685,0,0,93,1,360,579,1,1,1,0,26,20,999,80,17,12,83.250000
494,0,0,46,0,482,1015,0,5,0,1,11,13,1403,485,7,11,127.545454
440,0,0,18,0,590,562,0,0,0,0,19,10,2063,227,9,12,171.916667
622,0,1,0,0,8,49,0,0,0,0,0,0,0,0,4,0,0.000000
547,0,0,0,0,58,742,0,0,1,0,0,0,0,0,9,0,0.000000
95,0,0,69,0,376,373,0,1,0,1,20,6,1957,227,14,12,163.083333
141,0,0,9,0,226,226,0,0,0,1,10,1,784,33,17,10,78.400000
306,0,0,31,1,130,4,0,0,1,0,3,7,173,0,17,3,57.666667
375,0,0,98,0,615,586,0,1,0,1,13,15,2850,248,11,12,237.500000
596,0,1,0,0,14,78,0,0,0,0,0,0,0,0,0,0,0.000000
873,0,0,0,0,116,200,0,0,0,0,1,0,48,0,23,1,48.000000
521,0,1,0,0,1,19,0,0,0,1,0,0,0,0,7,0,0.000000
608,0,1,0,0,357,925,0,0,0,0,9,0,202,7,8,9,22.444444
701,0,1,0,0,88,472,0,0,0,0,0,0,0,0,18,0,0.000000
426,0,0,39,0,665,734,0,3,0,1,0,0,0,0,10,0,0.000000
825,0,0,0,0,19,118,0,0,0,0,0,0,0,0,4,0,0.000000
779,0,0,132,1,915,3489,1,1,0,0,96,38,992,29,14,12,82.666667
311,0,0,33,0,238,362,0,1,0,1,4,0,512,59,14,4,128.000000
593,0,1,0,0,202,266,0,0,0,0,3,0,236,6,14,3,78.666667
291,0,0,15,0,785,713,0,4,1,0,54,41,3573,263,18,12,297.750000
731,0,0,63,0,137,231,0,0,0,0,12,0,159,23,3,12,13.250000
84,0,0,61,0,659,965,1,8,1,0,17,15,2551,156,6,12,212.583333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,0,0,32,0,252,188,1,1,0,0,81,5,401,22,9,12,33.416667
775,0,0,122,0,169,45,1,1,0,0,64,0,801,179,12,12,66.750000
631,0,1,0,0,702,284,0,0,0,0,0,0,0,0,7,0,0.000000
611,0,0,44,0,52,36,0,0,0,0,0,0,0,0,0,0,0.000000
800,0,0,78,0,45,170,0,1,1,0,1,5,13,0,8,1,13.000000
509,0,0,0,0,47,156,0,0,0,0,0,0,0,0,9,0,0.000000
548,0,0,104,0,94,3,0,0,1,0,3,12,226,7,4,3,75.333333
257,0,0,36,0,573,656,0,3,0,1,16,12,3694,164,12,12,307.833333
866,0,0,0,0,195,375,0,0,0,0,0,0,0,0,20,0,0.000000
109,0,0,43,0,640,475,0,6,0,1,2,4,361,29,13,2,180.500000
312,0,0,29,0,502,475,0,5,0,1,16,18,1884,151,9,12,157.000000
156,0,0,10,0,223,349,0,0,0,0,1,0,66,4,11,1,66.000000
208,0,0,0,0,509,562,0,0,0,1,3,1,772,87,8,3,257.333333
132,0,0,0,0,34,10,1,0,0,0,6,6,158,13,3,6,26.333333
85,0,0,27,0,167,185,0,0,0,1,23,22,1035,119,0,12,86.250000
623,0,0,0,0,26,1151,0,0,0,0,2,0,2,0,0,2,1.000000
215,0,0,99,0,651,882,0,15,0,1,7,6,2038,135,13,7,291.142857
628,0,1,0,0,5,119,0,0,0,0,0,0,0,0,8,0,0.000000
318,0,0,24,0,637,700,0,0,0,1,0,0,0,0,13,0,0.000000
60,0,0,149,0,198,207,0,0,0,1,0,0,0,0,13,0,0.000000
641,0,0,121,0,169,561,0,0,0,0,0,0,0,0,7,0,0.000000
383,0,0,0,0,342,477,0,0,0,1,0,0,0,0,6,0,0.000000
493,0,0,0,0,420,593,0,0,0,1,4,0,899,31,9,4,224.750000
865,0,0,31,0,206,105,0,0,0,0,4,0,172,7,22,4,43.000000
543,0,0,87,0,9,125,0,1,0,1,6,0,16,0,7,6,2.666667
417,0,0,39,0,707,934,1,10,1,0,190,2,1867,56,9,12,155.583333
6,0,0,28,0,506,488,0,0,0,1,13,17,1603,98,22,12,133.583333
586,0,0,13,0,65,245,1,0,0,0,3,0,41,0,13,3,13.666667
221,0,0,0,0,200,273,0,0,0,1,1,0,103,20,10,1,103.000000
638,0,0,0,0,101,20,0,0,0,0,0,0,0,0,11,0,0.000000

In [6]:
svc = svm.SVC()
svc.fit(x_train, y_train)

SVC()

In [7]:
y_pred = svc.predict(x_test)
print(y_pred)

[1 1 1 0 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 0 1
 1 0 1 1 0 1 1 1 1 0 1 1 0 1 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0
 0 1 0 1 0 1 1 1 0 1 0 1 0 0 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 1 0 1 0 1 1 1 1 0 1 1 0
 0 0 1 0 1 1 1 1 0 1 1 1 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1
 0 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 0 1 1 0 1 1 1 1 1 0 0 0 0 1 0 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 0 0
 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 1 0 1 1 0 0 0 1 0 1 0 1 0 1 1 1
 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 0 1 1 0 0 0 1 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0
 1 0 0 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 1 1 1]

In [8]:
confusion_matrix(y_test, y_pred)

array([[105, 104],
       [ 13, 137]])

In [9]:
result = accuracy_score(y_test,y_pred)
print("Accuracy:",result*100)

Accuracy: 67.40947075208913

# KFold Validation

In [10]:
def accuracy(Y_pred,Y_test):
    Y_test=Y_test.values
    count=0
    for i in range(0,len(Y_pred)):
        if(Y_pred[i]==Y_test[i]):
            count=count+1
    print("accuracy of kfold :"+str((count/len(Y_pred))*100))
    return (count/len(Y_pred))*100


mean=0
import pandas as pd
from sklearn.model_selection import KFold
data=(data-data.min())/(data.max()-data.min())
data.drop('is_verified',inplace=True, axis=1)
Y_train=data["is_fake"]
X_train=data.loc[:, data.columns != 'is_fake']
cv = KFold(n_splits=4, random_state=1, shuffle=True)
kfold=cv.split(X_train, Y_train)
for k, (train, test) in enumerate(kfold):
    svc.fit(X_train.iloc[train, :], Y_train.iloc[train])
    Y_pred=svc.predict(X_train.iloc[test, :])
    mean=mean+accuracy(Y_pred,Y_train.iloc[test])
print(mean/4)

accuracy of kfold :85.71428571428571
accuracy of kfold :79.91071428571429
accuracy of kfold :85.71428571428571
accuracy of kfold :76.78571428571429
82.03125

# Sayooj B Kumar

## AM.EN.U4CSE19050